= Operator Certification Workflow
ifdef::env-github[]
:imagesdir:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]
:toc:
:toc-placement!:

Welcome Red Hat Connect for Technology Partners. This guide provides instructions on how to publish a certified Operator on the Red Hat Connect for Technology Partners web portal.

toc::[]

I think most people use Markdown when creating documentation on GitHub. Markdown is great and easy, but I often create technical documentation or training material where some of the additional semantics of Asciidoc are really helpful.

== Step One: Complete Questionnaire and Join SIG

== Step Two: Publish Container Image in Connect

== Step Three: Install Openshift Container Platform for Testing

== Step Four: Install Operator Framework 

== Step Five: Build Operator

== Step Six: Test Operator

== Step Seven: Certify Operator

== Step Eight: Post Certification


