= Operator Certification Workflow
ifdef::env-github[]
:imagesdir:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]
:toc:
:toc-placement!:

Welcome Red Hat Connect Technology Partners. This guide provides instructions on how to publish a certified Operator on the https://connect.redhat.com[Connect] web portal.

toc::[]


== Step One: Complete Questionnaire and Join SIG

First off, fill out the https://docs.google.com/forms/d/e/1FAIpQLSfEv47Vu_H-j_wQroOMMh0MIn_8lbDcmE_Lpj5YAGiNo0i_8g/viewform[Operator Framework Community Questionnaire]. The Red Hat Partner Connect team will use this to guage your Organization's experience with Operators and curate resources that will be most helpful for you. You will also be added to the Operator Framework community mailing list and special interest group (SIG). 

== Step Two: Publish Container Image in Connect

In order to certify your Operator, you must have a certified Container image published though Red Hat Connect and available on the https://access.redhat.com/containers[Red Hat Container Catalog].

We have an extensive guide that will walk you through certifying a Container image that can be found https://github.com/RHC4TP/documentation/tree/master/Container%20Zone%20-OpenShift[here].

== Step Three: Install Openshift Container Platform for Testing

Follow this https://docs.google.com/document/d/1XYTxY-iPrswP5HoZ9DQklUOfGTy9DCDHXcUbrqI--DA/edit#heading=h.gqtq4ip36gyx[guide] to setup OCP and configure for Operator functionality. 

== Step Four: Install Operator Framework 

== Step Five: Build Operator

== Step Six: Test Operator

== Step Seven: Certify Operator

== Step Eight: Post Certification


